/* ================================================================
   GlowGuide - Product Database (35 products) & Quiz Config
   ================================================================ */

const QUIZ_CONFIG = {
  steps: [
    {
      id: 'skinType',
      question: 'What best describes your skin type?',
      subtitle: 'Think about how your skin usually feels by midday.',
      options: [
        { id: 'dry',         icon: '\u{1F4A7}', label: 'Dry',         desc: 'Tight, flaky or rough - especially after washing.' },
        { id: 'oily',        icon: '\u2728',     label: 'Oily',        desc: 'Shiny by mid-morning, enlarged pores.' },
        { id: 'combination', icon: '\u{1F500}',  label: 'Combination', desc: 'Oily T-zone with dry or normal cheeks.' },
        { id: 'normal',      icon: '\u{1F33F}',  label: 'Normal',      desc: 'Balanced - not too oily or dry.' },
        { id: 'sensitive',   icon: '\u{1F534}',  label: 'Sensitive',   desc: 'Reacts easily - redness, stinging.' }
      ]
    },
    {
      id: 'concern',
      question: 'What is your primary skin concern?',
      subtitle: 'Choose the one you would most like to address.',
      options: [
        { id: 'acne',        icon: '\u{1FAE7}', label: 'Acne & Breakouts',         desc: 'Pimples, blackheads or clogged pores.' },
        { id: 'darkspots',   icon: '\u{1F311}', label: 'Dark Spots & Uneven Tone', desc: 'Hyperpigmentation, sun spots, post-acne marks.' },
        { id: 'ageing',      icon: '\u231B',     label: 'Fine Lines & Ageing',      desc: 'Wrinkles, firmness loss, dullness over time.' },
        { id: 'dehydration', icon: '\u{1F4A6}', label: 'Dehydration & Dryness',    desc: 'Lacks moisture, feels tight or looks dull.' },
        { id: 'dullness',    icon: '\u{1F31F}', label: 'Dullness & Glow',          desc: 'Looks tired, flat or lacks radiance.' }
      ]
    },
    {
      id: 'routine',
      question: 'How involved should your routine be?',
      subtitle: 'We will recommend the right number of products for your lifestyle.',
      options: [
        { id: 'minimal',  icon: '\u26A1',    label: 'Minimal (3 steps)',        desc: 'Cleanser + moisturiser + SPF. Quick, simple.' },
        { id: 'moderate', icon: '\u2696',     label: 'Moderate (5 steps)',       desc: 'Add a toner and serum to the basics.' },
        { id: 'full',     icon: '\u{1F319}', label: 'Full Routine (7+ steps)',  desc: 'Comprehensive AM/PM with multiple treatments.' }
      ]
    }
  ]
};

/* ================================================================
   PRODUCTS DATABASE - 35 products
   Each tagged by: skinTypes[], concerns[], step (order), routine tiers
   ================================================================ */
const PRODUCTS = [
  // ============ STEP 1: CLEANSERS ============
  {
    id: 'cl-01',
    name: 'Gentle Foaming Cleanser',
    brand: 'CeraVe',
    size: '236 ml',
    price: '\u20B9999',
    step: 1, stepLabel: 'Cleanser',
    timing: 'AM + PM',
    skinTypes: ['oily', 'combination', 'normal'],
    concerns: ['acne', 'darkspots', 'dullness'],
    tags: ['fragrance-free', 'non-comedogenic'],
    ingredients: ['Niacinamide', 'Ceramides NP/AP/EOP', 'Hyaluronic Acid'],
    rating: 4.7, reviews: 12400,
    color: 'blue', emoji: '\u{1F9F4}',
    reason: 'Removes excess oil without stripping moisture. Ceramides protect the barrier while niacinamide calms inflammation - ideal for {skinType} skin with {concern}.',
    howToUse: 'Wet face, massage a small pump for 30-60 seconds, rinse lukewarm. Use AM and PM.'
  },
  {
    id: 'cl-02',
    name: 'Hydrating Cream-to-Foam Cleanser',
    brand: 'La Roche-Posay',
    size: '200 ml',
    price: '\u20B91,299',
    step: 1, stepLabel: 'Cleanser',
    timing: 'AM + PM',
    skinTypes: ['dry', 'sensitive', 'normal'],
    concerns: ['dehydration', 'ageing', 'dullness'],
    tags: ['fragrance-free', 'dermatologist-tested'],
    ingredients: ['Glycerin', 'Niacinamide', 'Ceramide-3', 'Thermal Water'],
    rating: 4.6, reviews: 8700,
    color: 'blue', emoji: '\u{1F9F4}',
    reason: 'Cream texture cleanses without drying. Glycerin and ceramides replenish moisture - essential for {skinType} skin dealing with {concern}.',
    howToUse: 'Apply to damp skin, massage gently, rinse. AM and PM.'
  },
  {
    id: 'cl-03',
    name: 'SA Smoothing Cleanser',
    brand: 'CeraVe',
    size: '236 ml',
    price: '\u20B9999',
    step: 1, stepLabel: 'Cleanser',
    timing: 'PM only',
    skinTypes: ['oily', 'combination'],
    concerns: ['acne', 'dullness'],
    tags: ['fragrance-free', 'non-comedogenic'],
    ingredients: ['Salicylic Acid', 'Ceramides', 'Niacinamide'],
    rating: 4.5, reviews: 6200,
    color: 'green', emoji: '\u{1F9F4}',
    reason: 'Contains salicylic acid to unclog pores at the cleansing step. Perfect for {skinType} skin prone to {concern}.',
    howToUse: 'Use in PM only. Massage onto wet skin for 60 seconds, rinse thoroughly.'
  },
  {
    id: 'cl-04',
    name: 'Soy pH-Balanced Cleanser',
    brand: 'Fresh',
    size: '150 ml',
    price: '\u20B92,890',
    step: 1, stepLabel: 'Cleanser',
    timing: 'AM + PM',
    skinTypes: ['sensitive', 'dry', 'normal'],
    concerns: ['dehydration', 'darkspots', 'ageing'],
    tags: ['pH-balanced', 'gentle'],
    ingredients: ['Soy Proteins', 'Cucumber Extract', 'Rosewater'],
    rating: 4.4, reviews: 3100,
    color: 'green', emoji: '\u{1F9F4}',
    reason: 'Ultra-gentle pH-balanced formula that never disrupts the acid mantle. Ideal for {skinType} skin where harsh cleansers worsen {concern}.',
    howToUse: 'Apply to dry or damp skin, massage gently, rinse with water.'
  },

  // ============ STEP 2: TONERS / EXFOLIANTS ============
  {
    id: 'tn-01',
    name: 'BHA Liquid Exfoliant 2%',
    brand: "Paula's Choice",
    size: '118 ml',
    price: '\u20B92,750',
    step: 2, stepLabel: 'Exfoliating Toner',
    timing: 'PM (3x/week)',
    skinTypes: ['oily', 'combination', 'normal'],
    concerns: ['acne', 'darkspots', 'dullness'],
    tags: ['fragrance-free', 'cruelty-free'],
    ingredients: ['Salicylic Acid 2%', 'Green Tea Extract', 'Methylpropanediol'],
    rating: 4.8, reviews: 18500,
    color: 'green', emoji: '\u{1F9EA}',
    reason: 'BHA penetrates into pores to dissolve buildup. Reduces blackheads and evens tone over 4-8 weeks - highly effective for {skinType} skin targeting {concern}.',
    howToUse: 'After cleansing, apply to cotton pad, sweep across face. PM only, 3x per week. Follow with SPF next morning.'
  },
  {
    id: 'tn-02',
    name: 'Glycolic Acid 7% Toning Solution',
    brand: 'The Ordinary',
    size: '240 ml',
    price: '\u20B9790',
    step: 2, stepLabel: 'Exfoliating Toner',
    timing: 'PM (2-3x/week)',
    skinTypes: ['normal', 'combination', 'oily'],
    concerns: ['dullness', 'darkspots', 'ageing'],
    tags: ['vegan', 'cruelty-free'],
    ingredients: ['Glycolic Acid 7%', 'Aloe Vera', 'Ginseng Root', 'Tasmanian Pepperberry'],
    rating: 4.5, reviews: 14200,
    color: 'pink', emoji: '\u{1F9EA}',
    reason: 'AHA exfoliation removes dead surface cells to reveal brighter skin beneath. Excellent for {skinType} skin struggling with {concern}.',
    howToUse: 'Sweep onto face with cotton pad after cleansing, PM only. Start 2x/week, build to 3x. Always use SPF the next morning.'
  },
  {
    id: 'tn-03',
    name: 'Supple Preparation Unscented Toner',
    brand: 'Klairs',
    size: '180 ml',
    price: '\u20B91,590',
    step: 2, stepLabel: 'Hydrating Toner',
    timing: 'AM + PM',
    skinTypes: ['dry', 'sensitive', 'normal'],
    concerns: ['dehydration', 'ageing', 'dullness'],
    tags: ['fragrance-free', 'vegan', 'cruelty-free'],
    ingredients: ['Hyaluronic Acid', 'Beta-Glucan', 'Centella Asiatica'],
    rating: 4.5, reviews: 9800,
    color: 'blue', emoji: '\u{1F4A7}',
    reason: 'Hydrating toner that preps skin to absorb subsequent products. Multiple humectants draw water in - perfect for {skinType} skin with {concern}.',
    howToUse: 'Pat into slightly damp skin after cleansing. Layer 2-3 times for extra hydration.'
  },
  {
    id: 'tn-04',
    name: 'PHA Toner',
    brand: 'COSRX',
    size: '150 ml',
    price: '\u20B91,490',
    step: 2, stepLabel: 'Gentle Exfoliating Toner',
    timing: 'PM (daily)',
    skinTypes: ['sensitive', 'dry', 'normal'],
    concerns: ['dullness', 'dehydration', 'ageing'],
    tags: ['fragrance-free', 'gentle'],
    ingredients: ['Gluconolactone (PHA)', 'Betaine Salicylate', 'Allantoin'],
    rating: 4.4, reviews: 5200,
    color: 'blue', emoji: '\u{1F9EA}',
    reason: 'PHAs exfoliate gently without irritation - larger molecules that work on the surface only. Safe for {skinType} skin addressing {concern}.',
    howToUse: 'Apply to cotton pad after cleansing. Gentle enough for nightly use.'
  },

  // ============ STEP 3: SERUMS / TREATMENTS ============
  {
    id: 'sr-01',
    name: 'Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    size: '30 ml',
    price: '\u20B9590',
    step: 3, stepLabel: 'Treatment Serum',
    timing: 'AM + PM',
    skinTypes: ['oily', 'combination', 'normal', 'sensitive'],
    concerns: ['acne', 'darkspots', 'dullness'],
    tags: ['fragrance-free', 'vegan', 'cruelty-free'],
    ingredients: ['Niacinamide 10%', 'Zinc PCA 1%'],
    rating: 4.5, reviews: 32000,
    color: 'blue', emoji: '\u{1F9EA}',
    reason: 'Controls sebum, minimises pores, and fades marks over 4-8 weeks. Zinc regulates oil production - perfect for {skinType} skin with {concern}.',
    howToUse: 'Apply 2-3 drops to clean skin before moisturiser. AM and PM.'
  },
  {
    id: 'sr-02',
    name: '15% Vitamin C + E + Ferulic Acid',
    brand: 'The Inkey List',
    size: '30 ml',
    price: '\u20B91,050',
    step: 3, stepLabel: 'Antioxidant Serum',
    timing: 'AM only',
    skinTypes: ['normal', 'combination', 'dry', 'oily'],
    concerns: ['darkspots', 'dullness', 'ageing'],
    tags: ['vegan', 'cruelty-free'],
    ingredients: ['L-Ascorbic Acid 15%', 'Vitamin E', 'Ferulic Acid'],
    rating: 4.4, reviews: 8900,
    color: 'yellow', emoji: '\u{1F34A}',
    reason: 'Powerful antioxidant that brightens, fades existing spots and boosts SPF effectiveness. Ferulic acid stabilises the formula - great for {skinType} skin fighting {concern}.',
    howToUse: 'Apply 3-4 drops to clean dry skin in the morning. Wait 1 minute before moisturiser.'
  },
  {
    id: 'sr-03',
    name: 'Retinol 0.3% in Squalane',
    brand: 'The Ordinary',
    size: '30 ml',
    price: '\u20B9630',
    step: 3, stepLabel: 'Retinoid',
    timing: 'PM (2-3x/week)',
    skinTypes: ['normal', 'combination', 'oily', 'dry'],
    concerns: ['ageing', 'darkspots', 'acne'],
    tags: ['vegan', 'cruelty-free'],
    ingredients: ['Retinol 0.3%', 'Squalane'],
    rating: 4.3, reviews: 11500,
    color: 'pink', emoji: '\u{1F319}',
    reason: 'Gold-standard anti-ageing ingredient. Accelerates cell turnover to reduce lines and smooth texture. Squalane reduces irritation - suitable for {skinType} skin with {concern}.',
    howToUse: 'Apply pea-sized amount PM only, 2-3x per week to start. Build frequency over 6 weeks. Never mix with AHA/BHA same night.'
  },
  {
    id: 'sr-04',
    name: 'Hyaluronic Acid 2% + B5',
    brand: 'The Ordinary',
    size: '30 ml',
    price: '\u20B9690',
    step: 3, stepLabel: 'Hydrating Serum',
    timing: 'AM + PM',
    skinTypes: ['dry', 'sensitive', 'normal', 'combination'],
    concerns: ['dehydration', 'ageing', 'dullness'],
    tags: ['fragrance-free', 'vegan', 'cruelty-free'],
    ingredients: ['Multi-weight Hyaluronic Acid', 'Panthenol (B5)'],
    rating: 4.6, reviews: 24000,
    color: 'blue', emoji: '\u{1F4A6}',
    reason: 'Multi-molecular weight HA hydrates at different depths. Panthenol repairs and soothes - essential for {skinType} skin battling {concern}.',
    howToUse: 'Apply 2-3 drops to damp skin. MUST follow with moisturiser to seal hydration in.'
  },
  {
    id: 'sr-05',
    name: 'Alpha Arbutin 2% + HA',
    brand: 'The Ordinary',
    size: '30 ml',
    price: '\u20B9750',
    step: 3, stepLabel: 'Brightening Serum',
    timing: 'AM + PM',
    skinTypes: ['normal', 'combination', 'oily', 'dry', 'sensitive'],
    concerns: ['darkspots', 'dullness'],
    tags: ['fragrance-free', 'vegan'],
    ingredients: ['Alpha Arbutin 2%', 'Hyaluronic Acid'],
    rating: 4.4, reviews: 9800,
    color: 'yellow', emoji: '\u{1F31F}',
    reason: 'Alpha arbutin inhibits melanin production to fade dark spots without irritation. Gentler than hydroquinone - safe for {skinType} skin addressing {concern}.',
    howToUse: 'Apply a few drops to areas of concern AM and PM before moisturiser.'
  },
  {
    id: 'sr-06',
    name: 'Azelaic Acid Suspension 10%',
    brand: 'The Ordinary',
    size: '30 ml',
    price: '\u20B9690',
    step: 3, stepLabel: 'Treatment Serum',
    timing: 'AM or PM',
    skinTypes: ['oily', 'combination', 'sensitive', 'normal'],
    concerns: ['acne', 'darkspots', 'dullness'],
    tags: ['vegan', 'cruelty-free'],
    ingredients: ['Azelaic Acid 10%'],
    rating: 4.3, reviews: 7600,
    color: 'pink', emoji: '\u{1F9EA}',
    reason: 'Anti-inflammatory that fights acne bacteria AND fades hyperpigmentation simultaneously. Dual-action is perfect for {skinType} skin with {concern}.',
    howToUse: 'Apply a thin layer after water-based serums. Can be used AM or PM.'
  },
  {
    id: 'sr-07',
    name: 'Snail Mucin 96% Power Essence',
    brand: 'COSRX',
    size: '100 ml',
    price: '\u20B91,799',
    step: 3, stepLabel: 'Repairing Essence',
    timing: 'AM + PM',
    skinTypes: ['dry', 'sensitive', 'normal', 'combination'],
    concerns: ['dehydration', 'ageing', 'dullness', 'darkspots'],
    tags: ['fragrance-free', 'dermatologist-tested'],
    ingredients: ['Snail Secretion Filtrate 96%', 'Betaine', 'Allantoin'],
    rating: 4.6, reviews: 28000,
    color: 'green', emoji: '\u{1F40C}',
    reason: 'Snail mucin is rich in glycoproteins that repair and hydrate simultaneously. Reduces redness and speeds healing - excellent for {skinType} skin with {concern}.',
    howToUse: 'Dispense 2-3 pumps, pat into skin after toner. AM and PM.'
  },
  {
    id: 'sr-08',
    name: 'Buffet Multi-Technology Peptide Serum',
    brand: 'The Ordinary',
    size: '30 ml',
    price: '\u20B91,350',
    step: 3, stepLabel: 'Anti-Ageing Serum',
    timing: 'AM + PM',
    skinTypes: ['normal', 'dry', 'combination'],
    concerns: ['ageing', 'dullness', 'dehydration'],
    tags: ['fragrance-free', 'vegan'],
    ingredients: ['Matrixyl 3000', 'Matrixyl Synthe-6', 'SYN-AKE', 'Hyaluronic Acid'],
    rating: 4.5, reviews: 15000,
    color: 'purple', emoji: '\u{1F52C}',
    reason: 'Multi-peptide complex signals skin to produce more collagen. Targets multiple signs of ageing at once - ideal for {skinType} skin concerned with {concern}.',
    howToUse: 'Apply a few drops to face and neck AM and PM before heavier products.'
  },
  {
    id: 'sr-09',
    name: 'Centella Unscented Serum',
    brand: 'PURITO',
    size: '60 ml',
    price: '\u20B91,390',
    step: 3, stepLabel: 'Calming Serum',
    timing: 'AM + PM',
    skinTypes: ['sensitive', 'dry', 'normal'],
    concerns: ['acne', 'dehydration', 'dullness'],
    tags: ['fragrance-free', 'vegan', 'cruelty-free'],
    ingredients: ['Centella Asiatica 49%', 'Madecassic Acid', 'Asiaticoside'],
    rating: 4.5, reviews: 6800,
    color: 'green', emoji: '\u{1F33F}',
    reason: 'Centella calms irritation and strengthens the skin barrier. Anti-inflammatory without being drying - great for {skinType} skin with {concern}.',
    howToUse: 'Apply 2-3 drops to clean skin. Can be mixed with moisturiser if preferred.'
  },

  // ============ STEP 4: MOISTURISERS ============
  {
    id: 'mo-01',
    name: 'Hydro Boost Water Gel',
    brand: 'Neutrogena',
    size: '50 ml',
    price: '\u20B9899',
    step: 4, stepLabel: 'Moisturiser',
    timing: 'AM + PM',
    skinTypes: ['oily', 'combination', 'normal'],
    concerns: ['acne', 'dullness', 'dehydration', 'darkspots'],
    tags: ['oil-free', 'non-comedogenic', 'fragrance-free'],
    ingredients: ['Hyaluronic Acid', 'Glycerin', 'Dimethicone'],
    rating: 4.5, reviews: 19000,
    color: 'blue', emoji: '\u{1F4A7}',
    reason: 'Oil-free gel-cream that hydrates without clogging pores. Lightweight enough for {skinType} skin while addressing moisture needs related to {concern}.',
    howToUse: 'Apply a coin-sized amount after serums. AM and PM. Press into skin gently.'
  },
  {
    id: 'mo-02',
    name: 'Toleriane Double Repair Moisturiser',
    brand: 'La Roche-Posay',
    size: '75 ml',
    price: '\u20B91,499',
    step: 4, stepLabel: 'Moisturiser',
    timing: 'AM + PM',
    skinTypes: ['dry', 'sensitive', 'normal'],
    concerns: ['dehydration', 'ageing', 'dullness', 'darkspots'],
    tags: ['fragrance-free', 'non-comedogenic', 'dermatologist-tested'],
    ingredients: ['Ceramide-3', 'Niacinamide', 'Glycerin', 'Prebiotic Thermal Water'],
    rating: 4.7, reviews: 14500,
    color: 'green', emoji: '\u{1F33F}',
    reason: 'Ceramides + niacinamide repair the barrier and lock moisture in for 48 hours. Clinically proven for sensitive skin - perfect for {skinType} skin with {concern}.',
    howToUse: 'Apply generously AM and PM. Use a thicker layer at night for overnight recovery.'
  },
  {
    id: 'mo-03',
    name: 'Moisturising Lotion PM',
    brand: 'CeraVe',
    size: '52 ml',
    price: '\u20B91,099',
    step: 4, stepLabel: 'Night Moisturiser',
    timing: 'PM only',
    skinTypes: ['normal', 'oily', 'combination'],
    concerns: ['acne', 'dehydration', 'dullness'],
    tags: ['fragrance-free', 'non-comedogenic', 'oil-free'],
    ingredients: ['Niacinamide', 'Ceramides', 'MVE Technology'],
    rating: 4.5, reviews: 11200,
    color: 'blue', emoji: '\u{1F319}',
    reason: 'MVE delivery system releases moisturising ingredients gradually overnight. Non-greasy formula suitable for {skinType} skin dealing with {concern}.',
    howToUse: 'Apply as last step of PM routine. Slightly richer than day moisturiser.'
  },
  {
    id: 'mo-04',
    name: 'Ultra Facial Cream',
    brand: "Kiehl's",
    size: '50 ml',
    price: '\u20B92,800',
    step: 4, stepLabel: 'Moisturiser',
    timing: 'AM + PM',
    skinTypes: ['dry', 'normal', 'sensitive'],
    concerns: ['dehydration', 'ageing', 'dullness'],
    tags: ['dermatologist-tested'],
    ingredients: ['Squalane', 'Glycerin', 'Glacial Glycoprotein'],
    rating: 4.6, reviews: 8900,
    color: 'blue', emoji: '\u{1F9CA}',
    reason: 'Rich but non-greasy formula with squalane for deep nourishment. Locks in hydration all day - excellent for {skinType} skin experiencing {concern}.',
    howToUse: 'Apply morning and evening over serums. A little goes a long way.'
  },

  // ============ STEP 5: EYE CREAM ============
  {
    id: 'ey-01',
    name: 'Caffeine Solution 5% + EGCG',
    brand: 'The Ordinary',
    size: '30 ml',
    price: '\u20B9690',
    step: 5, stepLabel: 'Eye Serum',
    timing: 'AM + PM',
    skinTypes: ['oily', 'combination', 'dry', 'normal', 'sensitive'],
    concerns: ['ageing', 'dullness', 'dehydration'],
    tags: ['fragrance-free', 'vegan', 'cruelty-free'],
    ingredients: ['Caffeine 5%', 'EGCG (Green Tea)', 'Hyaluronic Acid'],
    rating: 4.3, reviews: 21000,
    color: 'pink', emoji: '\u{1F441}\uFE0F',
    reason: 'Caffeine constricts blood vessels to reduce puffiness and dark circles. EGCG provides antioxidant protection - effective for {skinType} skin with {concern} around the eyes.',
    howToUse: 'Dab a tiny amount under each eye with ring finger. AM and PM. Do not rub.'
  },
  {
    id: 'ey-02',
    name: 'Retinol Eye Cream 0.1%',
    brand: 'RoC',
    size: '15 ml',
    price: '\u20B91,590',
    step: 5, stepLabel: 'Eye Cream',
    timing: 'PM only',
    skinTypes: ['normal', 'dry', 'combination'],
    concerns: ['ageing', 'darkspots'],
    tags: ['dermatologist-tested', 'clinically-proven'],
    ingredients: ['Retinol 0.1%', 'Hyaluronic Acid', 'Vitamin E'],
    rating: 4.4, reviews: 5600,
    color: 'purple', emoji: '\u{1F441}\uFE0F',
    reason: 'Clinical-strength retinol specifically formulated for the delicate eye area. Targets crow\'s feet and under-eye lines for {skinType} skin with {concern}.',
    howToUse: 'Apply a tiny dot under each eye PM only. Use ring finger, tap gently. Build up to nightly use.'
  },

  // ============ STEP 6: SPF ============
  {
    id: 'sp-01',
    name: 'Ultra-Light Fluid SPF 50+',
    brand: 'La Roche-Posay Anthelios',
    size: '50 ml',
    price: '\u20B91,799',
    step: 6, stepLabel: 'Sunscreen',
    timing: 'AM only',
    skinTypes: ['oily', 'combination', 'normal'],
    concerns: ['acne', 'darkspots', 'ageing', 'dullness'],
    tags: ['non-comedogenic', 'oil-free', 'fragrance-free'],
    ingredients: ['Mexoryl SX/XL', 'Tinosorb S', 'Niacinamide'],
    rating: 4.7, reviews: 16800,
    color: 'yellow', emoji: '\u2600\uFE0F',
    reason: 'Invisible, ultra-light SPF that never clogs pores. Essential for {skinType} skin - UV damage worsens {concern} significantly without protection.',
    howToUse: 'Apply generously (2 finger lengths) as last AM step. Reapply every 2 hours if outdoors.'
  },
  {
    id: 'sp-02',
    name: 'UV Aqua Rich Watery Essence SPF 50+',
    brand: 'Biore',
    size: '50 g',
    price: '\u20B91,099',
    step: 6, stepLabel: 'Sunscreen',
    timing: 'AM only',
    skinTypes: ['dry', 'sensitive', 'normal'],
    concerns: ['dehydration', 'ageing', 'darkspots', 'dullness'],
    tags: ['lightweight', 'hydrating'],
    ingredients: ['Hyaluronic Acid', 'Royal Jelly Extract', 'UV Block'],
    rating: 4.7, reviews: 22000,
    color: 'yellow', emoji: '\u2600\uFE0F',
    reason: 'Watery texture absorbs instantly and adds a hydration layer. Feels like skincare, not sunscreen - ideal for {skinType} skin needing protection against {concern}.',
    howToUse: 'Shake well. Apply liberally as final AM step. Lightweight enough to layer under makeup.'
  },
  {
    id: 'sp-03',
    name: 'Mineral Sunscreen SPF 50',
    brand: 'Elta MD UV Clear',
    size: '48 g',
    price: '\u20B92,499',
    step: 6, stepLabel: 'Sunscreen',
    timing: 'AM only',
    skinTypes: ['sensitive', 'oily', 'combination'],
    concerns: ['acne', 'darkspots', 'ageing'],
    tags: ['fragrance-free', 'mineral/physical', 'non-comedogenic'],
    ingredients: ['Zinc Oxide 9%', 'Niacinamide', 'Hyaluronic Acid'],
    rating: 4.6, reviews: 9800,
    color: 'yellow', emoji: '\u2600\uFE0F',
    reason: 'Mineral (zinc oxide) SPF that calms rather than irritates. Niacinamide controls oil and redness - made for {skinType} skin dealing with {concern}.',
    howToUse: 'Apply generously to face each morning. Mineral filters sit on the skin surface - no wait time needed.'
  },
  {
    id: 'sp-04',
    name: 'Hydrating SPF 50 Cream',
    brand: 'Eucerin',
    size: '50 ml',
    price: '\u20B91,350',
    step: 6, stepLabel: 'Sunscreen',
    timing: 'AM only',
    skinTypes: ['dry', 'normal', 'sensitive'],
    concerns: ['dehydration', 'ageing', 'dullness'],
    tags: ['fragrance-free', 'dermatologist-recommended'],
    ingredients: ['Glycerin', 'Hyaluronic Acid', 'Licochalcone A'],
    rating: 4.5, reviews: 7200,
    color: 'yellow', emoji: '\u2600\uFE0F',
    reason: 'Moisturising SPF that doubles as a day cream. Provides long-lasting hydration while protecting against UV damage that accelerates {concern} in {skinType} skin.',
    howToUse: 'Can replace separate moisturiser + SPF in the morning. Apply generously to face and neck.'
  },

  // ============ STEP 7: MASKS / TREATMENTS (for full routines) ============
  {
    id: 'mk-01',
    name: 'AHA 30% + BHA 2% Peeling Solution',
    brand: 'The Ordinary',
    size: '30 ml',
    price: '\u20B9690',
    step: 7, stepLabel: 'Weekly Peel',
    timing: 'PM (1x/week)',
    skinTypes: ['oily', 'combination', 'normal'],
    concerns: ['acne', 'darkspots', 'dullness'],
    tags: ['vegan', 'cruelty-free'],
    ingredients: ['Glycolic Acid 30%', 'Salicylic Acid 2%', 'Hyaluronic Acid Crosspolymer'],
    rating: 4.5, reviews: 19000,
    color: 'pink', emoji: '\u{1F9EA}',
    reason: 'Powerful weekly treatment that dissolves dead skin and deeply unclogs pores. Maximum exfoliation for {skinType} skin fighting {concern}. Not for sensitive skin.',
    howToUse: 'Apply to clean dry skin for MAX 10 minutes. Rinse thoroughly. Once per week ONLY. Do not use on broken, sensitive or sunburned skin.'
  },
  {
    id: 'mk-02',
    name: 'Honey Overnight Mask',
    brand: 'COSRX',
    size: '60 ml',
    price: '\u20B91,699',
    step: 7, stepLabel: 'Sleeping Mask',
    timing: 'PM (2-3x/week)',
    skinTypes: ['dry', 'sensitive', 'normal'],
    concerns: ['dehydration', 'dullness', 'ageing'],
    tags: ['propolis', 'nourishing'],
    ingredients: ['Propolis Extract 87%', 'Beeswax', 'Ceramides'],
    rating: 4.5, reviews: 8200,
    color: 'yellow', emoji: '\u{1F36F}',
    reason: 'Propolis overnight mask creates a healing, hydrating seal while you sleep. Wake up with plumper, glowing skin - transformative for {skinType} skin with {concern}.',
    howToUse: 'Apply a thin layer as the very last step of PM routine, 2-3x per week. Wash off in the morning.'
  },
  {
    id: 'mk-03',
    name: 'Clay Mask Purifying',
    brand: 'Innisfree',
    size: '100 ml',
    price: '\u20B9899',
    step: 7, stepLabel: 'Weekly Mask',
    timing: 'PM (1-2x/week)',
    skinTypes: ['oily', 'combination'],
    concerns: ['acne', 'dullness'],
    tags: ['natural', 'volcanic clay'],
    ingredients: ['Jeju Volcanic Ash', 'Kaolin', 'Bentonite'],
    rating: 4.4, reviews: 11000,
    color: 'green', emoji: '\u{1F30B}',
    reason: 'Volcanic clay draws out excess oil and impurities from deep within pores. Leaves skin matte and refined - great for {skinType} skin dealing with {concern}.',
    howToUse: 'Apply even layer to clean skin, avoiding eye area. Leave 10-15 minutes until dry. Rinse with warm water.'
  },
  {
    id: 'mk-04',
    name: 'Overnight Recovery Cream',
    brand: 'Kiehl\'s',
    size: '50 ml',
    price: '\u20B93,450',
    step: 7, stepLabel: 'Night Treatment',
    timing: 'PM (nightly)',
    skinTypes: ['dry', 'normal', 'sensitive'],
    concerns: ['ageing', 'dehydration', 'dullness'],
    tags: ['evening-primrose-oil', 'anti-ageing'],
    ingredients: ['Squalane', 'Evening Primrose Oil', 'Vitamin E', 'Lavender Oil'],
    rating: 4.5, reviews: 6500,
    color: 'purple', emoji: '\u{1F319}',
    reason: 'Rich overnight treatment that deeply nourishes while you sleep. Evening primrose oil restores elasticity - ideal for {skinType} skin experiencing {concern}.',
    howToUse: 'Apply as the last step of PM routine. Use nightly for cumulative results.'
  },

  // ============ ADDITIONAL PRODUCTS FOR COVERAGE ============
  {
    id: 'sr-10',
    name: 'Tranexamic Acid Serum',
    brand: 'Good Molecules',
    size: '30 ml',
    price: '\u20B91,050',
    step: 3, stepLabel: 'Brightening Serum',
    timing: 'AM + PM',
    skinTypes: ['normal', 'oily', 'combination', 'sensitive'],
    concerns: ['darkspots', 'dullness', 'acne'],
    tags: ['fragrance-free', 'cruelty-free'],
    ingredients: ['Tranexamic Acid 5%', 'Niacinamide', 'Kojic Acid'],
    rating: 4.4, reviews: 4200,
    color: 'yellow', emoji: '\u{1F31F}',
    reason: 'Tranexamic acid prevents melanin transfer to the skin surface. Three brightening actives work together - effective for {skinType} skin targeting {concern}.',
    howToUse: 'Apply 2-3 drops AM and PM. Layer under moisturiser. Pairs well with SPF.'
  },
  {
    id: 'sr-11',
    name: 'Granactive Retinoid 2% Emulsion',
    brand: 'The Ordinary',
    size: '30 ml',
    price: '\u20B9890',
    step: 3, stepLabel: 'Retinoid',
    timing: 'PM only',
    skinTypes: ['sensitive', 'dry', 'normal'],
    concerns: ['ageing', 'dullness', 'darkspots'],
    tags: ['fragrance-free', 'vegan'],
    ingredients: ['Hydroxypinacolone Retinoate', 'Squalane', 'Jojoba Oil'],
    rating: 4.4, reviews: 8500,
    color: 'pink', emoji: '\u{1F319}',
    reason: 'Next-gen retinoid that delivers anti-ageing results with less irritation than traditional retinol. No peeling period - safe for {skinType} skin addressing {concern}.',
    howToUse: 'Apply 2-3 drops to clean skin in PM. Start every other night. Can be used nightly once tolerated.'
  },
  {
    id: 'mo-05',
    name: 'Great Barrier Relief Moisturiser',
    brand: 'Krave Beauty',
    size: '45 ml',
    price: '\u20B92,490',
    step: 4, stepLabel: 'Barrier Repair',
    timing: 'AM + PM',
    skinTypes: ['sensitive', 'dry', 'combination'],
    concerns: ['dehydration', 'acne', 'dullness'],
    tags: ['fragrance-free', 'fungal-acne-safe'],
    ingredients: ['Tamanu Oil', 'Safflower Oil', 'Niacinamide 2%'],
    rating: 4.6, reviews: 5400,
    color: 'green', emoji: '\u{1F9F4}',
    reason: 'Tamanu oil heals and strengthens a compromised barrier. When the barrier is healthy, all other concerns improve - essential for {skinType} skin with {concern}.',
    howToUse: 'Apply a small pump over serums AM and PM. Can be mixed with another moisturiser if needed.'
  },
  {
    id: 'cl-05',
    name: 'Low pH Good Morning Gel Cleanser',
    brand: 'COSRX',
    size: '150 ml',
    price: '\u20B9950',
    step: 1, stepLabel: 'Cleanser',
    timing: 'AM',
    skinTypes: ['oily', 'combination', 'normal', 'sensitive'],
    concerns: ['acne', 'dullness', 'dehydration'],
    tags: ['low-pH', 'gentle', 'vegan'],
    ingredients: ['Tea Tree Oil', 'BHA 0.5%', 'Betaine Salicylate'],
    rating: 4.4, reviews: 13500,
    color: 'green', emoji: '\u{1F9F4}',
    reason: 'Low pH formula that respects your acid mantle while gently cleansing AM buildup. Tea tree provides mild antibacterial action for {skinType} skin with {concern}.',
    howToUse: 'Use as AM cleanser. Small amount, gentle massage, rinse. pH 5.0-6.0.'
  },
  {
    id: 'tn-05',
    name: 'Mandelic Acid 5% Toner',
    brand: 'By Wishtrend',
    size: '120 ml',
    price: '\u20B91,790',
    step: 2, stepLabel: 'Gentle Exfoliating Toner',
    timing: 'PM (daily)',
    skinTypes: ['sensitive', 'combination', 'dry'],
    concerns: ['darkspots', 'dullness', 'ageing'],
    tags: ['fragrance-free', 'gentle AHA'],
    ingredients: ['Mandelic Acid 5%', 'Panthenol', 'Centella Asiatica'],
    rating: 4.4, reviews: 3800,
    color: 'pink', emoji: '\u{1F9EA}',
    reason: 'Mandelic acid has the largest AHA molecule - exfoliates slowly and evenly without irritation. Ideal for {skinType} skin that needs gentle treatment for {concern}.',
    howToUse: 'Apply to cotton pad after cleansing. Sweep across face. Gentle enough for nightly use on most skin types.'
  }
];

/* ================================================================
   DISPLAY LABELS
   ================================================================ */
const CONCERN_LABELS = {
  acne: 'Acne & Breakouts',
  darkspots: 'Dark Spots & Uneven Tone',
  ageing: 'Fine Lines & Ageing',
  dehydration: 'Dehydration & Dryness',
  dullness: 'Dullness & Glow'
};

const SKIN_TYPE_LABELS = {
  dry: 'Dry',
  oily: 'Oily',
  combination: 'Combination',
  normal: 'Normal',
  sensitive: 'Sensitive'
};

const ROUTINE_LABELS = {
  minimal: 'Minimal (3 steps)',
  moderate: 'Moderate (5 steps)',
  full: 'Full Routine (7+ steps)'
};
